//
//  File.swift
//
//
//  Created by morse on 2023/9/8.
//

/// T9 拼音映射
public let t9PinyinMapping = [
  "A": ["a", "b", "c", "2"],
  "AA": ["ba", "ca"],
  "AAG": ["bai", "cai"],
  "AAM": ["ban", "bao", "can", "cao"],
  "AAMG": ["bang", "cang"],
  "AD": ["ce"],
  "ADG": ["bei"],
  "ADM": ["ben", "cen"],
  "ADMG": ["beng", "ceng"],
  "AG": ["ai", "bi", "ci"],
  "AGA": ["cha"],
  "AGAG": ["chai"],
  "AGAM": ["bian", "biao", "chan", "chao"],
  "AGAMG": ["chang"],
  "AGD": ["bie", "che"],
  "AGDM": ["chen"],
  "AGDMG": ["cheng"],
  "AGG": ["chi"],
  "AGM": ["bin"],
  "AGMG": ["bing"],
  "AGMMG": ["chong"],
  "AGMT": ["chou"],
  "AGT": ["chu"],
  "AGTA": ["chua"],
  "AGTAG": ["chuai"],
  "AGTAM": ["chuan"],
  "AGTAMG": ["chuang"],
  "AGTG": ["chui"],
  "AGTM": ["chun", "chuo"],
  "AM": ["an", "ao", "bo"],
  "AMG": ["ang"],
  "AMMG": ["cong"],
  "AMT": ["cou"],
  "AT": ["bu", "cu"],
  "ATAM": ["cuan"],
  "ATG": ["cui"],
  "ATM": ["cun", "cuo"],
  "D": ["d", "e", "f", "3"],
  "DA": ["da", "fa"],
  "DAG": ["dai"],
  "DAM": ["dan", "dao", "fan"],
  "DAMG": ["dang", "fang"],
  "DD": ["de"],
  "DDG": ["dei", "fei"],
  "DDM": ["den", "fen"],
  "DDMG": ["deng", "feng"],
  "DG": ["di", "ei"],
  "DGA": ["dia"],
  "DGAM": ["dian", "diao"],
  "DGD": ["die"],
  "DGMG": ["ding"],
  "DGT": ["diu"],
  "DM": ["en", "fo"],
  "DMG": ["eng"],
  "DMMG": ["dong"],
  "DMT": ["dou", "fou"],
  "DP": ["er"],
  "DT": ["du", "fu"],
  "DTAM": ["duan"],
  "DTG": ["dui"],
  "DTM": ["dun", "duo"],
  "G": ["g", "h", "i", "4"],
  "GA": ["ga", "ha"],
  "GAG": ["gai", "hai"],
  "GAM": ["gan", "gao", "han", "hao"],
  "GAMG": ["gang", "hang"],
  "GD": ["ge", "he"],
  "GDG": ["gei", "hei"],
  "GDM": ["gen", "hen"],
  "GDMG": ["geng", "heng"],
  "GM": ["hm"],
  "GMMG": ["gong", "hong"],
  "GMT": ["gou", "hou"],
  "GT": ["gu", "hu"],
  "GTA": ["gua", "hua"],
  "GTAG": ["guai", "huai"],
  "GTAM": ["guan", "huan"],
  "GTAMG": ["guang", "huang"],
  "GTG": ["gui", "hui"],
  "GTM": ["gun", "guo", "hun", "huo"],
  "J": ["j", "k", "l", "5"],
  "JA": ["ka", "la"],
  "JAG": ["kai", "lai"],
  "JAM": ["kan", "kao", "lan", "lao"],
  "JAMG": ["kang", "lang"],
  "JD": ["ke", "le"],
  "JDG": ["kei", "lei"],
  "JDM": ["ken"],
  "JDMG": ["keng", "leng"],
  "JG": ["ji", "li"],
  "JGA": ["jia", "lia"],
  "JGAM": ["jian", "jiao", "lian", "liao"],
  "JGAMG": ["jiang", "liang"],
  "JGD": ["jie", "lie"],
  "JGM": ["jin", "lin"],
  "JGMG": ["jing", "ling"],
  "JGMMG": ["jiong"],
  "JGT": ["jiu", "liu"],
  "JM": ["lo"],
  "JMMG": ["kong", "long"],
  "JMT": ["kou", "lou"],
  "JT": ["ju", "ku", "lu", "lv"],
  "JTA": ["kua"],
  "JTAG": ["kuai"],
  "JTAM": ["juan", "kuan", "luan"],
  "JTAMG": ["kuang"],
  "JTD": ["jue", "lve"],
  "JTG": ["kui"],
  "JTM": ["jun", "kun", "kuo", "lun", "luo"],
  "M": ["m", "n", "o", "6"],
  "MA": ["ma", "na"],
  "MAG": ["mai", "nai"],
  "MAM": ["man", "mao", "nan", "nao"],
  "MAMG": ["mang", "nang"],
  "MD": ["me", "ne"],
  "MDG": ["mei", "nei"],
  "MDM": ["men", "nen"],
  "MDMG": ["meng", "neng"],
  "MG": ["mi", "ni"],
  "MGA": ["nia"],
  "MGAM": ["mian", "miao", "nian", "niao"],
  "MGAMG": ["niang"],
  "MGD": ["mie", "nie"],
  "MGM": ["min", "nin"],
  "MGMG": ["ming", "ning"],
  "MGT": ["miu", "niu"],
  "MM": ["mo"],
  "MMMG": ["nong"],
  "MMT": ["mou", "nou"],
  "MT": ["mu", "nu", "nv", "ou"],
  "MTAM": ["nuan"],
  "MTD": ["nve"],
  "MTM": ["nuo"],
  "P": ["p", "q", "r", "s", "7"],
  "PA": ["pa", "sa"],
  "PAG": ["pai", "sai"],
  "PAM": ["pan", "pao", "ran", "rao", "san", "sao"],
  "PAMG": ["pang", "rang", "sang"],
  "PD": ["re", "se"],
  "PDG": ["pei"],
  "PDM": ["pen", "ren", "sen"],
  "PDMG": ["peng", "reng", "seng"],
  "PG": ["pi", "qi", "ri", "si"],
  "PGA": ["qia", "sha"],
  "PGAG": ["shai"],
  "PGAM": ["pian", "piao", "qian", "qiao", "shan", "shao"],
  "PGAMG": ["qiang", "shang"],
  "PGD": ["pie", "qie", "she"],
  "PGDG": ["shei"],
  "PGDM": ["shen"],
  "PGDMG": ["sheng"],
  "PGG": ["shi"],
  "PGM": ["pin", "qin"],
  "PGMG": ["ping", "qing"],
  "PGMMG": ["qiong"],
  "PGMT": ["shou"],
  "PGT": ["qiu", "shu"],
  "PGTA": ["shua"],
  "PGTAG": ["shuai"],
  "PGTAM": ["shuan"],
  "PGTAMG": ["shuang"],
  "PGTG": ["shui"],
  "PGTM": ["shun", "shuo"],
  "PM": ["po"],
  "PMMG": ["rong", "song"],
  "PMT": ["pou", "rou", "sou"],
  "PT": ["pu", "qu", "ru", "su"],
  "PTAM": ["quan", "ruan", "suan"],
  "PTD": ["que"],
  "PTG": ["rui", "sui"],
  "PTM": ["qun", "run", "ruo", "sun", "suo"],
  "T": ["t", "u", "v", "8"],
  "TA": ["ta"],
  "TAG": ["tai"],
  "TAM": ["tan", "tao"],
  "TAMG": ["tang"],
  "TD": ["te"],
  "TDMG": ["teng"],
  "TG": ["ti"],
  "TGAM": ["tian", "tiao"],
  "TGD": ["tie"],
  "TGMG": ["ting"],
  "TMMG": ["tong"],
  "TMT": ["tou"],
  "TT": ["tu"],
  "TTAM": ["tuan"],
  "TTG": ["tui"],
  "TTM": ["tun", "tuo"],
  "W": ["w", "x", "y", "z", "9"],
  "WA": ["wa", "ya", "za"],
  "WAG": ["wai", "zai"],
  "WAM": ["wan", "yan", "yao", "zan", "zao"],
  "WAMG": ["wang", "yang", "zang"],
  "WD": ["ye", "ze"],
  "WDG": ["wei", "zei"],
  "WDM": ["wen", "zen"],
  "WDMG": ["weng", "zeng"],
  "WG": ["xi", "yi", "zi"],
  "WGA": ["xia", "zha"],
  "WGAG": ["zhai"],
  "WGAM": ["xian", "xiao", "zhan", "zhao"],
  "WGAMG": ["xiang", "zhang"],
  "WGD": ["xie", "zhe"],
  "WGDG": ["zhei"],
  "WGDM": ["zhen"],
  "WGDMG": ["zheng"],
  "WGG": ["zhi"],
  "WGM": ["xin", "yin"],
  "WGMG": ["xing", "ying"],
  "WGMMG": ["xiong", "zhong"],
  "WGMT": ["zhou"],
  "WGT": ["xiu", "zhu"],
  "WGTA": ["zhua"],
  "WGTAG": ["zhuai"],
  "WGTAM": ["zhuan"],
  "WGTAMG": ["zhuang"],
  "WGTG": ["zhui"],
  "WGTM": ["zhun", "zhuo"],
  "WM": ["wo", "yo"],
  "WMMG": ["yong", "zong"],
  "WMT": ["you", "zou"],
  "WT": ["wu", "xu", "yu", "zu"],
  "WTAM": ["xuan", "yuan", "zuan"],
  "WTD": ["xue", "yue"],
  "WTG": ["zui"],
  "WTM": ["xun", "yun", "zun", "zuo"],
]

/// T9 拼音 keys 的 Trie 结构
/// 用于匹配用户输入
public let t9PinyinTrie: Trie<String> = {
  let trie = Trie<String>()
  t9PinyinMapping.keys.forEach {
    trie.insert($0)
  }
  return trie
}()
