//
//  File.swift
//
//
//  Created by morse on 2023/9/8.
//

/// T9 到拼音的映射
public let t9ToPinyinMapping = [
  "A": ["a", "b", "c", "2"],
  "AA": ["ba", "ca"],
  "AAG": ["bai", "cai"],
  "AAM": ["ban", "bao", "can", "cao"],
  "AAMG": ["bang", "cang"],
  "AD": ["ce"],
  "ADG": ["bei"],
  "ADM": ["ben", "cen"],
  "ADMG": ["beng", "ceng"],
  "AG": ["ai", "bi", "ci"],
  "AGA": ["cha"],
  "AGAG": ["chai"],
  "AGAM": ["bian", "biao", "chan", "chao"],
  "AGAMG": ["chang"],
  "AGD": ["bie", "che"],
  "AGDM": ["chen"],
  "AGDMG": ["cheng"],
  "AGG": ["chi"],
  "AGM": ["bin"],
  "AGMG": ["bing"],
  "AGMMG": ["chong"],
  "AGMT": ["chou"],
  "AGT": ["chu"],
  "AGTA": ["chua"],
  "AGTAG": ["chuai"],
  "AGTAM": ["chuan"],
  "AGTAMG": ["chuang"],
  "AGTG": ["chui"],
  "AGTM": ["chun", "chuo"],
  "AM": ["an", "ao", "bo"],
  "AMG": ["ang"],
  "AMMG": ["cong"],
  "AMT": ["cou"],
  "AT": ["bu", "cu"],
  "ATAM": ["cuan"],
  "ATG": ["cui"],
  "ATM": ["cun", "cuo"],
  "D": ["d", "e", "f", "3"],
  "DA": ["da", "fa"],
  "DAG": ["dai"],
  "DAM": ["dan", "dao", "fan"],
  "DAMG": ["dang", "fang"],
  "DD": ["de"],
  "DDG": ["dei", "fei"],
  "DDM": ["den", "fen"],
  "DDMG": ["deng", "feng"],
  "DG": ["di", "ei"],
  "DGA": ["dia"],
  "DGAM": ["dian", "diao"],
  "DGD": ["die"],
  "DGMG": ["ding"],
  "DGT": ["diu"],
  "DM": ["en", "fo"],
  "DMG": ["eng"],
  "DMMG": ["dong"],
  "DMT": ["dou", "fou"],
  "DP": ["er"],
  "DT": ["du", "fu"],
  "DTAM": ["duan"],
  "DTG": ["dui"],
  "DTM": ["dun", "duo"],
  "G": ["g", "h", "i", "4"],
  "GA": ["ga", "ha"],
  "GAG": ["gai", "hai"],
  "GAM": ["gan", "gao", "han", "hao"],
  "GAMG": ["gang", "hang"],
  "GD": ["ge", "he"],
  "GDG": ["gei", "hei"],
  "GDM": ["gen", "hen"],
  "GDMG": ["geng", "heng"],
  "GM": ["hm"],
  "GMMG": ["gong", "hong"],
  "GMT": ["gou", "hou"],
  "GT": ["gu", "hu"],
  "GTA": ["gua", "hua"],
  "GTAG": ["guai", "huai"],
  "GTAM": ["guan", "huan"],
  "GTAMG": ["guang", "huang"],
  "GTG": ["gui", "hui"],
  "GTM": ["gun", "guo", "hun", "huo"],
  "J": ["j", "k", "l", "5"],
  "JA": ["ka", "la"],
  "JAG": ["kai", "lai"],
  "JAM": ["kan", "kao", "lan", "lao"],
  "JAMG": ["kang", "lang"],
  "JD": ["ke", "le"],
  "JDG": ["kei", "lei"],
  "JDM": ["ken"],
  "JDMG": ["keng", "leng"],
  "JG": ["ji", "li"],
  "JGA": ["jia", "lia"],
  "JGAM": ["jian", "jiao", "lian", "liao"],
  "JGAMG": ["jiang", "liang"],
  "JGD": ["jie", "lie"],
  "JGM": ["jin", "lin"],
  "JGMG": ["jing", "ling"],
  "JGMMG": ["jiong"],
  "JGT": ["jiu", "liu"],
  "JM": ["lo"],
  "JMMG": ["kong", "long"],
  "JMT": ["kou", "lou"],
  "JT": ["ju", "ku", "lu", "lv"],
  "JTA": ["kua"],
  "JTAG": ["kuai"],
  "JTAM": ["juan", "kuan", "luan"],
  "JTAMG": ["kuang"],
  "JTD": ["jue", "lve"],
  "JTG": ["kui"],
  "JTM": ["jun", "kun", "kuo", "lun", "luo"],
  "M": ["m", "n", "o", "6"],
  "MA": ["ma", "na"],
  "MAG": ["mai", "nai"],
  "MAM": ["man", "mao", "nan", "nao"],
  "MAMG": ["mang", "nang"],
  "MD": ["me", "ne"],
  "MDG": ["mei", "nei"],
  "MDM": ["men", "nen"],
  "MDMG": ["meng", "neng"],
  "MG": ["mi", "ni"],
  "MGA": ["nia"],
  "MGAM": ["mian", "miao", "nian", "niao"],
  "MGAMG": ["niang"],
  "MGD": ["mie", "nie"],
  "MGM": ["min", "nin"],
  "MGMG": ["ming", "ning"],
  "MGT": ["miu", "niu"],
  "MM": ["mo"],
  "MMMG": ["nong"],
  "MMT": ["mou", "nou"],
  "MT": ["mu", "nu", "nv", "ou"],
  "MTAM": ["nuan"],
  "MTD": ["nve"],
  "MTM": ["nuo"],
  "P": ["p", "q", "r", "s", "7"],
  "PA": ["pa", "sa"],
  "PAG": ["pai", "sai"],
  "PAM": ["pan", "pao", "ran", "rao", "san", "sao"],
  "PAMG": ["pang", "rang", "sang"],
  "PD": ["re", "se"],
  "PDG": ["pei"],
  "PDM": ["pen", "ren", "sen"],
  "PDMG": ["peng", "reng", "seng"],
  "PG": ["pi", "qi", "ri", "si"],
  "PGA": ["qia", "sha"],
  "PGAG": ["shai"],
  "PGAM": ["pian", "piao", "qian", "qiao", "shan", "shao"],
  "PGAMG": ["qiang", "shang"],
  "PGD": ["pie", "qie", "she"],
  "PGDG": ["shei"],
  "PGDM": ["shen"],
  "PGDMG": ["sheng"],
  "PGG": ["shi"],
  "PGM": ["pin", "qin"],
  "PGMG": ["ping", "qing"],
  "PGMMG": ["qiong"],
  "PGMT": ["shou"],
  "PGT": ["qiu", "shu"],
  "PGTA": ["shua"],
  "PGTAG": ["shuai"],
  "PGTAM": ["shuan"],
  "PGTAMG": ["shuang"],
  "PGTG": ["shui"],
  "PGTM": ["shun", "shuo"],
  "PM": ["po"],
  "PMMG": ["rong", "song"],
  "PMT": ["pou", "rou", "sou"],
  "PT": ["pu", "qu", "ru", "su"],
  "PTAM": ["quan", "ruan", "suan"],
  "PTD": ["que"],
  "PTG": ["rui", "sui"],
  "PTM": ["qun", "run", "ruo", "sun", "suo"],
  "T": ["t", "u", "v", "8"],
  "TA": ["ta"],
  "TAG": ["tai"],
  "TAM": ["tan", "tao"],
  "TAMG": ["tang"],
  "TD": ["te"],
  "TDMG": ["teng"],
  "TG": ["ti"],
  "TGAM": ["tian", "tiao"],
  "TGD": ["tie"],
  "TGMG": ["ting"],
  "TMMG": ["tong"],
  "TMT": ["tou"],
  "TT": ["tu"],
  "TTAM": ["tuan"],
  "TTG": ["tui"],
  "TTM": ["tun", "tuo"],
  "W": ["w", "x", "y", "z", "9"],
  "WA": ["wa", "ya", "za"],
  "WAG": ["wai", "zai"],
  "WAM": ["wan", "yan", "yao", "zan", "zao"],
  "WAMG": ["wang", "yang", "zang"],
  "WD": ["ye", "ze"],
  "WDG": ["wei", "zei"],
  "WDM": ["wen", "zen"],
  "WDMG": ["weng", "zeng"],
  "WG": ["xi", "yi", "zi"],
  "WGA": ["xia", "zha"],
  "WGAG": ["zhai"],
  "WGAM": ["xian", "xiao", "zhan", "zhao"],
  "WGAMG": ["xiang", "zhang"],
  "WGD": ["xie", "zhe"],
  "WGDG": ["zhei"],
  "WGDM": ["zhen"],
  "WGDMG": ["zheng"],
  "WGG": ["zhi"],
  "WGM": ["xin", "yin"],
  "WGMG": ["xing", "ying"],
  "WGMMG": ["xiong", "zhong"],
  "WGMT": ["zhou"],
  "WGT": ["xiu", "zhu"],
  "WGTA": ["zhua"],
  "WGTAG": ["zhuai"],
  "WGTAM": ["zhuan"],
  "WGTAMG": ["zhuang"],
  "WGTG": ["zhui"],
  "WGTM": ["zhun", "zhuo"],
  "WM": ["wo", "yo"],
  "WMMG": ["yong", "zong"],
  "WMT": ["you", "zou"],
  "WT": ["wu", "xu", "yu", "zu"],
  "WTAM": ["xuan", "yuan", "zuan"],
  "WTD": ["xue", "yue"],
  "WTG": ["zui"],
  "WTM": ["xun", "yun", "zun", "zuo"],
]

/// 拼音到T9的映射
public let pinyinToT9Mapping = [
  "a": "A",
  "b": "A",
  "c": "A",
  "ai": "AG",
  "an": "AM",
  "ang": "AMG",
  "ao": "AM",
  "ba": "AA",
  "bai": "AAG",
  "ban": "AAM",
  "bang": "AAMG",
  "bao": "AAM",
  "bei": "ADG",
  "ben": "ADM",
  "beng": "ADMG",
  "bi": "AG",
  "bian": "AGAM",
  "biao": "AGAM",
  "bie": "AGD",
  "bin": "AGM",
  "bing": "AGMG",
  "bo": "AM",
  "bu": "AT",
  "ca": "AA",
  "cai": "AAG",
  "can": "AAM",
  "cang": "AAMG",
  "cao": "AAM",
  "ce": "AD",
  "cen": "ADM",
  "ceng": "ADMG",
  "cha": "AGA",
  "chai": "AGAG",
  "chan": "AGAM",
  "chang": "AGAMG",
  "chao": "AGAM",
  "che": "AGD",
  "chen": "AGDM",
  "cheng": "AGDMG",
  "chi": "AGG",
  "chong": "AGMMG",
  "chou": "AGMT",
  "chu": "AGT",
  "chua": "AGTA",
  "chuai": "AGTAG",
  "chuan": "AGTAM",
  "chuang": "AGTAMG",
  "chui": "AGTG",
  "chun": "AGTM",
  "chuo": "AGTM",
  "ci": "AG",
  "cong": "AMMG",
  "cou": "AMT",
  "cu": "AT",
  "cuan": "ATAM",
  "cui": "ATG",
  "cun": "ATM",
  "cuo": "ATM",
  "da": "DA",
  "dai": "DAG",
  "dan": "DAM",
  "dang": "DAMG",
  "dao": "DAM",
  "de": "DD",
  "dei": "DDG",
  "den": "DDM",
  "deng": "DDMG",
  "di": "DG",
  "dia": "DGA",
  "dian": "DGAM",
  "diao": "DGAM",
  "die": "DGD",
  "ding": "DGMG",
  "diu": "DGT",
  "dong": "DMMG",
  "dou": "DMT",
  "du": "DT",
  "duan": "DTAM",
  "dui": "DTG",
  "dun": "DTM",
  "duo": "DTM",
  "d": "D",
  "e": "D",
  "f": "D",
  "ei": "DG",
  "en": "DM",
  "eng": "DMG",
  "er": "DP",
  "fa": "DA",
  "fan": "DAM",
  "fang": "DAMG",
  "fei": "DDG",
  "fen": "DDM",
  "feng": "DDMG",
  "fo": "DM",
  "fou": "DMT",
  "fu": "DT",
  "g": "G",
  "h": "G",
  "i": "G",
  "ga": "GA",
  "gai": "GAG",
  "gan": "GAM",
  "gang": "GAMG",
  "gao": "GAM",
  "ge": "GD",
  "gei": "GDG",
  "gen": "GDM",
  "geng": "GDMG",
  "gong": "GMMG",
  "gou": "GMT",
  "gu": "GT",
  "gua": "GTA",
  "guai": "GTAG",
  "guan": "GTAM",
  "guang": "GTAMG",
  "gui": "GTG",
  "gun": "GTM",
  "guo": "GTM",
  "ha": "GA",
  "hai": "GAG",
  "han": "GAM",
  "hang": "GAMG",
  "hao": "GAM",
  "he": "GD",
  "hei": "GDG",
  "hen": "GDM",
  "heng": "GDMG",
  "hm": "GM",
  "hong": "GMMG",
  "hou": "GMT",
  "hu": "GT",
  "hua": "GTA",
  "huai": "GTAG",
  "huan": "GTAM",
  "huang": "GTAMG",
  "hui": "GTG",
  "hun": "GTM",
  "huo": "GTM",
  "j": "J",
  "k": "J",
  "l": "J",
  "ji": "JG",
  "jia": "JGA",
  "jian": "JGAM",
  "jiang": "JGAMG",
  "jiao": "JGAM",
  "jie": "JGD",
  "jin": "JGM",
  "jing": "JGMG",
  "jiong": "JGMMG",
  "jiu": "JGT",
  "ju": "JT",
  "juan": "JTAM",
  "jue": "JTD",
  "jun": "JTM",
  "ka": "JA",
  "kai": "JAG",
  "kan": "JAM",
  "kang": "JAMG",
  "kao": "JAM",
  "ke": "JD",
  "kei": "JDG",
  "ken": "JDM",
  "keng": "JDMG",
  "kong": "JMMG",
  "kou": "JMT",
  "ku": "JT",
  "kua": "JTA",
  "kuai": "JTAG",
  "kuan": "JTAM",
  "kuang": "JTAMG",
  "kui": "JTG",
  "kun": "JTM",
  "kuo": "JTM",
  "la": "JA",
  "lai": "JAG",
  "lan": "JAM",
  "lang": "JAMG",
  "lao": "JAM",
  "le": "JD",
  "lei": "JDG",
  "leng": "JDMG",
  "li": "JG",
  "lia": "JGA",
  "lian": "JGAM",
  "liang": "JGAMG",
  "liao": "JGAM",
  "lie": "JGD",
  "lin": "JGM",
  "ling": "JGMG",
  "liu": "JGT",
  "lo": "JM",
  "long": "JMMG",
  "lou": "JMT",
  "lu": "JT",
  "luan": "JTAM",
  "lun": "JTM",
  "luo": "JTM",
  "lv": "JT",
  "lve": "JTD",
  "m": "M",
  "n": "M",
  "o": "M",
  "ma": "MA",
  "mai": "MAG",
  "man": "MAM",
  "mang": "MAMG",
  "mao": "MAM",
  "me": "MD",
  "mei": "MDG",
  "men": "MDM",
  "meng": "MDMG",
  "mi": "MG",
  "mian": "MGAM",
  "miao": "MGAM",
  "mie": "MGD",
  "min": "MGM",
  "ming": "MGMG",
  "miu": "MGT",
  "mo": "MM",
  "mou": "MMT",
  "mu": "MT",
  "na": "MA",
  "nai": "MAG",
  "nan": "MAM",
  "nang": "MAMG",
  "nao": "MAM",
  "ne": "MD",
  "nei": "MDG",
  "nen": "MDM",
  "neng": "MDMG",
  "ni": "MG",
  "nia": "MGA",
  "nian": "MGAM",
  "niang": "MGAMG",
  "niao": "MGAM",
  "nie": "MGD",
  "nin": "MGM",
  "ning": "MGMG",
  "niu": "MGT",
  "nong": "MMMG",
  "nou": "MMT",
  "nu": "MT",
  "nuan": "MTAM",
  "nuo": "MTM",
  "nv": "MT",
  "nve": "MTD",
  "ou": "MT",
  "p": "P",
  "q": "P",
  "r": "P",
  "s": "P",
  "pa": "PA",
  "pai": "PAG",
  "pan": "PAM",
  "pang": "PAMG",
  "pao": "PAM",
  "pei": "PDG",
  "pen": "PDM",
  "peng": "PDMG",
  "pi": "PG",
  "pian": "PGAM",
  "piao": "PGAM",
  "pie": "PGD",
  "pin": "PGM",
  "ping": "PGMG",
  "po": "PM",
  "pou": "PMT",
  "pu": "PT",
  "qi": "PG",
  "qia": "PGA",
  "qian": "PGAM",
  "qiang": "PGAMG",
  "qiao": "PGAM",
  "qie": "PGD",
  "qin": "PGM",
  "qing": "PGMG",
  "qiong": "PGMMG",
  "qiu": "PGT",
  "qu": "PT",
  "quan": "PTAM",
  "que": "PTD",
  "qun": "PTM",
  "ran": "PAM",
  "rang": "PAMG",
  "rao": "PAM",
  "re": "PD",
  "ren": "PDM",
  "reng": "PDMG",
  "ri": "PG",
  "rong": "PMMG",
  "rou": "PMT",
  "ru": "PT",
  "ruan": "PTAM",
  "rui": "PTG",
  "run": "PTM",
  "ruo": "PTM",
  "sa": "PA",
  "sai": "PAG",
  "san": "PAM",
  "sang": "PAMG",
  "sao": "PAM",
  "se": "PD",
  "sen": "PDM",
  "seng": "PDMG",
  "sha": "PGA",
  "shai": "PGAG",
  "shan": "PGAM",
  "shang": "PGAMG",
  "shao": "PGAM",
  "she": "PGD",
  "shei": "PGDG",
  "shen": "PGDM",
  "sheng": "PGDMG",
  "shi": "PGG",
  "shou": "PGMT",
  "shu": "PGT",
  "shua": "PGTA",
  "shuai": "PGTAG",
  "shuan": "PGTAM",
  "shuang": "PGTAMG",
  "shui": "PGTG",
  "shun": "PGTM",
  "shuo": "PGTM",
  "si": "PG",
  "song": "PMMG",
  "sou": "PMT",
  "su": "PT",
  "suan": "PTAM",
  "sui": "PTG",
  "sun": "PTM",
  "suo": "PTM",
  "t": "T",
  "u": "T",
  "v": "T",
  "ta": "TA",
  "tai": "TAG",
  "tan": "TAM",
  "tang": "TAMG",
  "tao": "TAM",
  "te": "TD",
  "teng": "TDMG",
  "ti": "TG",
  "tian": "TGAM",
  "tiao": "TGAM",
  "tie": "TGD",
  "ting": "TGMG",
  "tong": "TMMG",
  "tou": "TMT",
  "tu": "TT",
  "tuan": "TTAM",
  "tui": "TTG",
  "tun": "TTM",
  "tuo": "TTM",
  "w": "W",
  "x": "W",
  "y": "W",
  "z": "W",
  "wa": "WA",
  "wai": "WAG",
  "wan": "WAM",
  "wang": "WAMG",
  "wei": "WDG",
  "wen": "WDM",
  "weng": "WDMG",
  "wo": "WM",
  "wu": "WT",
  "xi": "WG",
  "xia": "WGA",
  "xian": "WGAM",
  "xiang": "WGAMG",
  "xiao": "WGAM",
  "xie": "WGD",
  "xin": "WGM",
  "xing": "WGMG",
  "xiong": "WGMMG",
  "xiu": "WGT",
  "xu": "WT",
  "xuan": "WTAM",
  "xue": "WTD",
  "xun": "WTM",
  "ya": "WA",
  "yan": "WAM",
  "yang": "WAMG",
  "yao": "WAM",
  "ye": "WD",
  "yi": "WG",
  "yin": "WGM",
  "ying": "WGMG",
  "yo": "WM",
  "yong": "WMMG",
  "you": "WMT",
  "yu": "WT",
  "yuan": "WTAM",
  "yue": "WTD",
  "yun": "WTM",
  "za": "WA",
  "zai": "WAG",
  "zan": "WAM",
  "zang": "WAMG",
  "zao": "WAM",
  "ze": "WD",
  "zei": "WDG",
  "zen": "WDM",
  "zeng": "WDMG",
  "zha": "WGA",
  "zhai": "WGAG",
  "zhan": "WGAM",
  "zhang": "WGAMG",
  "zhao": "WGAM",
  "zhe": "WGD",
  "zhei": "WGDG",
  "zhen": "WGDM",
  "zheng": "WGDMG",
  "zhi": "WGG",
  "zhong": "WGMMG",
  "zhou": "WGMT",
  "zhu": "WGT",
  "zhua": "WGTA",
  "zhuai": "WGTAG",
  "zhuan": "WGTAM",
  "zhuang": "WGTAMG",
  "zhui": "WGTG",
  "zhun": "WGTM",
  "zhuo": "WGTM",
  "zi": "WG",
  "zong": "WMMG",
  "zou": "WMT",
  "zu": "WT",
  "zuan": "WTAM",
  "zui": "WTG",
  "zun": "WTM",
  "zuo": "WTM",
]

/// T9 拼音 keys 的 Trie 结构
/// 用于匹配用户输入
public let t9PinyinTrie: Trie<String> = {
  let trie = Trie<String>()
  t9ToPinyinMapping.keys.forEach {
    trie.insert($0)
  }
  return trie
}()
